ec2_name                   = "bastion_host"
ec2_type                   = "t2.micro"
vpc_cidr                   = "10.0.0.0/16"
ssh_cidr_blocks            = ["10.0.0.0/16"]
vpc_id                     = "terraform-test"
subnet_id                  = "terraform-subnet"
key_name                   = "terraform-test-key"
public_subnet_cidr_block   = "10.0.1.0/24"
private_subnet_cidr_blocks = ["10.0.2.0/24", "10.0.3.0/24"]
